admin_menu:
  - name: "sidebar.admin.users"
    path: "/admin/users"

#  - name: "Quản lý bài viết"
#    path: "/admin/posts"
#
#  - name: "Quản lý nhãn"
#    path: "/admin/tags"

  - name: "sidebar.admin.prizes"
    path: "/admin/prizes"

  - name: "sidebar.admin.select_numbers"
    path: "/admin/select_numbers"

  - name: "sidebar.admin.winners"
    path: "/admin/winners"